In [9]:
import pandas as pd
import numpy as np
from IPython.display import display

In [4]:
poll_df = pd.read_csv("president_polls.csv")
poll_df.head()

,poll_id,pollster_id,pollster,sponsor_ids,sponsors,display_name,pollster_rating_id,pollster_rating_name,fte_grade,methodology,...,election_date,stage,nationwide_batch,ranked_choice_reallocated,ranked_choice_round,party,answer,candidate_id,candidate_name,pct
0,84924,1102,Emerson,NaN,NaN,Emerson College,88,Emerson College,A-,IVR/Online Panel/Email,...,11/5/24,general,False,False,NaN,DEM,Biden,19368,Joe Biden,43.2
1,84924,1102,Emerson,NaN,NaN,Emerson College,88,Emerson College,A-,IVR/Online Panel/Email,...,11/5/24,general,False,False,NaN,REP,Trump,16651,Donald Trump,47.4
2,84924,1102,Emerson,NaN,NaN,Emerson College,88,Emerson College,A-,IVR/Online Panel/Email,...,11/5/24,general,False,False,NaN,DEM,Biden,19368,Joe Biden,36.7
3,84924,1102,Emerson,NaN,NaN,Emerson College,88,Emerson College,A-,IVR/Online Panel/Email,...,11/5/24,general,False,False,NaN,REP,Trump,16651,Donald Trump,43.4
4,84924,1102,Emerson,NaN,NaN,Emerson College,88,Emerson College,A-,IVR/Online Panel/Email,...,11/5/24,general,False,False,NaN,IND,Kennedy,31042,Robert F. Kennedy,6.5

In [12]:
display(poll_df.describe())
display(poll_df.describe(include=['O']))

,poll_id,pollster_id,pollster_rating_id,transparency_score,sponsor_candidate_id,question_id,sample_size,subpopulation,source,race_id,cycle,seat_number,seat_name,ranked_choice_round,candidate_id,pct
count,4701.000000,4701.000000,4701.000000,1483.000000,12.000000,4701.000000,4683.000000,0.0,201.0,4701.000000,4701.0,4701.0,0.0,0.0,4701.000000,4701.000000
mean,82617.245054,1180.246118,318.478196,6.326028,28577.333333,173615.275899,1989.485159,NaN,538.0,8890.099766,2024.0,0.0,NaN,NaN,18689.582217,40.181306
std,2162.172796,461.429597,193.146211,2.303128,5571.600282,11268.228945,1979.608948,NaN,0.0,45.692064,0.0,0.0,NaN,NaN,3391.162062,8.982626
min,74681.000000,57.000000,3.000000,1.000000,16651.000000,140691.000000,300.000000,NaN,538.0,8749.000000,2024.0,0.0,NaN,NaN,16638.000000,0.700000
25%,81725.000000,1075.000000,195.000000,4.000000,30788.000000,165909.000000,1000.000000,NaN,538.0,8889.000000,2024.0,0.0,NaN,NaN,16651.000000,38.000000
50%,83142.000000,1189.000000,260.000000,6.000000,30951.500000,175314.000000,1180.000000,NaN,538.0,8914.000000,2024.0,0.0,NaN,NaN,16661.000000,42.000000
75%,84382.000000,1562.000000,448.000000,9.000000,31061.000000,183509.000000,2059.000000,NaN,538.0,8914.000000,2024.0,0.0,NaN,NaN,19368.000000,44.200000
max,84924.000000,1832.000000,809.000000,10.000000,31061.000000,188203.000000,26230.000000,NaN,538.0,8914.000000,2024.0,0.0,NaN,NaN,31116.000000,67.600000

,pollster,sponsor_ids,sponsors,display_name,pollster_rating_name,fte_grade,methodology,state,start_date,end_date,...,notes,url,internal,partisan,office_type,election_date,stage,party,answer,candidate_name
count,4701,1744,1744,4701,4701,4523,4604,1321,4701,4701,...,52,4699,10,240,4701,4701,4701,4701,4701,4701
unique,115,113,113,115,109,12,35,46,551,552,...,6,747,1,4,1,1,1,7,43,43
top,Morning Consult,763,Harvard CAPS,Morning Consult,Morning Consult,B-,Online Panel,Georgia,10/22/23,11/3/23,...,split sample,https://pro.morningconsult.com/analysis/2024-g...,True,REP,U.S. President,11/5/24,general,DEM,Biden,Joe Biden
freq,900,213,213,900,900,1160,2726,118,134,154,...,20,418,10,162,4701,4701,4701,2226,1980,1980

In [43]:
import pandas as pd
import glob
import os

path = r"C:\Users\KT\Documents\ds_portfolio\kamala_vs_harris\*.csv"
csv_files = glob.glob(path)

dfs = {os.path.basename(file): pd.read_csv(file) for file in csv_files}
print("dfs:", dfs.keys())
print(dfs['candidates.csv'].head())

dfs: dict_keys(['candidates.csv', 'delegate_counts.csv', 'favorability_polls.csv', 'generic_ballot_polls.csv', 'president_polls.csv', 'primaries_and_caucuses.csv'])
         party                 name date_announced date_withdrawn
0     democrat        Dean Phillips     10/26/2023       3/6/2024
1     democrat  Marianne Williamson       3/4/2023       2/7/2024
2     democrat            Joe Biden      4/25/2023       7/2/2024
3     democrat        Kamala Harris       7/1/2024            NaN
4  independent          Cornel West       6/5/2023            NaN